# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/Master_constraints/PYNQ-Z1_C.xdc

# Block Designs: C:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/rsa_soc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc || ORIG_REF_NAME==rsa_soc} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_rsa_acc_0/rsa_soc_rsa_acc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_acc_0 || ORIG_REF_NAME==rsa_soc_rsa_acc_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_rsa_dma_0/rsa_soc_rsa_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_dma_0 || ORIG_REF_NAME==rsa_soc_rsa_dma_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_processing_system7_0_0/rsa_soc_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_processing_system7_0_0 || ORIG_REF_NAME==rsa_soc_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_rst_ps7_0_100M_0/rsa_soc_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==rsa_soc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_axi_smc_0/rsa_soc_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_axi_smc_0 || ORIG_REF_NAME==rsa_soc_axi_smc_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_ps7_0_axi_periph_0/rsa_soc_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==rsa_soc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_xbar_0/rsa_soc_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_xbar_0 || ORIG_REF_NAME==rsa_soc_xbar_0} -quiet] -quiet

# IP: c:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rsa_soc_auto_pc_0 || ORIG_REF_NAME==rsa_soc_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/rsa_soc_ooc.xdc

# XDC: C:/Users/student/Documents/GitHub/TFE4141/rsa_term_project/RSA_soc/boards/rsa_soc_ooc.xdc
